orbs:
  hello-build: circleci/hello-build@0.0.9
version: 2.1
workflows:
  Hello Workflow:
    jobs:
      - hello-build/hello-build

  Every 20m:
    triggers:
      - schedule:
          cron: "0,20,40 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - hello-build/hello-build
